# Setup this config file before production run

# Glassnode API
GLASSNODE:
  API_KEY: ""

# Bybit exchange
BYBIT:
  apiKey: ""
  secret: ""
  max_pos: 0.006

# Underlying Asset
ASSET:
  cex_symbol: "BTCUSDT"
  glassnode_symbol: "BTC"
  since: 1672502400   # GMT: Sunday, December 1, 2024 4:59:41 PM by https://epochconverter.com
  timeframe: "1h"

# Strategy setting - total ratio of all strategy should be 1 for portfolio management ; x,y - optimized params of each strategy
# put ratio = 0 to disabled that strategy

# Strategy 1: Use ETH price data to predict BTC price.
STRAT1:
  ratio: 0.33
  x: 800
  y: 0.5
  api: "https://api.glassnode.com/v1/metrics/market/price_usd_close"
  api_symbol: "ETH"

# Strategy 2: Predict BTC price based on USDC balance distribution.
STRAT2:
  ratio: 0.33
  x: 3000
  y: 0.3
  api: "https://api.glassnode.com/v1/metrics/distribution/balance_exchanges"
  api_symbol: "USDC"

# Strategy 3: Net Unrealized Profit/Loss (NUPL), hr
STRAT3:
  ratio: 0.34
  x: 3000
  y: 0.75
  api: "https://api.glassnode.com/v1/metrics/indicators/net_unrealized_profit_loss"
  api_symbol: "BTC"